# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        MainWindow.setStyleSheet("*{\n"
"    font-family: Helvetica;\n"
"    font-weight: bold;\n"
"    border: 0;\n"
"}\n"
"\n"
"\n"
"#page_login {\n"
"    border-image: url(\'assets/images/bck.jpg\') 0 0 0 0 stretch stretch;    \n"
"}\n"
"\n"
"/* tab bar styles */\n"
"\n"
"QTabWidget::pane {\n"
"    border-top: 2px solid #C2C7CB;\n"
"}\n"
"\n"
"QTabBar {\n"
"    background-color: #C2C7CB;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #0F0F0F;\n"
"    color: white;\n"
"    border-bottom-color: #C2C7CB;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: rgb(17, 132, 224);\n"
"}\n"
"QTabBar::tab:selected {\n"
"    border-bottom-color: #C2C7CB;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px;\n"
"}\n"
"\n"
"/* end of tab bar */\n"
"/* settings tab */\n"
"\n"
"#account_tab {\n"
"    background-color: white;\n"
"}\n"
"\n"
"Line {\n"
"    color: black;\n"
"    background-color: black;\n"
"}\n"
"\n"
"/* end of settings tab*/\n"
"\n"
"/* charts tab */\n"
"\n"
"#charts_tab {\n"
"    background-color: white;\n"
"}\n"
"\n"
"/* end of charts tab*/\n"
"#messages_tab {\n"
"    background-color: rgb(211, 215, 207)\n"
"}\n"
"\n"
"#loginWrapper {\n"
"    background-color: rgba(0, 0, 0, 0.7);\n"
"    border: 0;\n"
"}\n"
"\n"
"#loginHeader{\n"
"    color: rgb(17, 132, 224);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background: transparent;\n"
"    border: 0 ;\n"
"    border-bottom: 1px solid rgb(186, 189, 182);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 0;\n"
"    background-color: rgb(17, 132, 224);\n"
"}\n"
"\n"
"#createButton {\n"
"    background-color: rgb(65, 208, 124);\n"
"}\n"
"\n"
"#loginButton {\n"
"    background-color: rgb(17, 132, 224);\n"
"}\n"
"\n"
"#backButton {\n"
"    border: 0;\n"
"}\n"
"\n"
"#admin_delete_messages{\n"
"    background-color: rgb(164, 0, 0);\n"
"}\n"
"\n"
"#sendButton {\n"
"    background-color: rgb(17, 132, 224);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"#sendButton:hover {\n"
"    background-color: rgb(107, 159, 255);\n"
"}\n"
"\n"
"#messages {\n"
"    border: 0;\n"
"    background-color: white;\n"
"}\n"
"\n"
"#messageInput {\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: white;\n"
"}\n"
"\n"
"#logOut {\n"
"    background-color: rgb(239, 41, 41);\n"
"}\n"
"\n"
"/* drop down */\n"
"\n"
"QComboBox::item {\n"
"    background-color: rgba(0, 0, 0, 0.4)\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(assets/images/arrow_down.png);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: 0;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"    border: 0;\n"
"}\n"
"\n"
"/* end of drop down */\n"
"\n"
"")
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-10, 0, 611, 501))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.loginWrapper = QtWidgets.QFrame(self.page_login)
        self.loginWrapper.setGeometry(QtCore.QRect(150, 80, 351, 341))
        self.loginWrapper.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.loginWrapper.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginWrapper.setFrameShadow(QtWidgets.QFrame.Plain)
        self.loginWrapper.setObjectName("loginWrapper")
        self.loginButton = QtWidgets.QPushButton(self.loginWrapper)
        self.loginButton.setGeometry(QtCore.QRect(220, 290, 89, 25))
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setObjectName("loginButton")
        self.inputUsername = QtWidgets.QLineEdit(self.loginWrapper)
        self.inputUsername.setGeometry(QtCore.QRect(40, 130, 270, 25))
        self.inputUsername.setStyleSheet("")
        self.inputUsername.setObjectName("inputUsername")
        self.inputPassword = QtWidgets.QLineEdit(self.loginWrapper)
        self.inputPassword.setGeometry(QtCore.QRect(40, 210, 270, 25))
        self.inputPassword.setMouseTracking(True)
        self.inputPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPassword.setClearButtonEnabled(False)
        self.inputPassword.setObjectName("inputPassword")
        self.createButton = QtWidgets.QPushButton(self.loginWrapper)
        self.createButton.setGeometry(QtCore.QRect(40, 290, 89, 25))
        self.createButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.createButton.setObjectName("createButton")
        self.loginHeader = QtWidgets.QLabel(self.loginWrapper)
        self.loginHeader.setGeometry(QtCore.QRect(46, 50, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.loginHeader.setFont(font)
        self.loginHeader.setTextFormat(QtCore.Qt.AutoText)
        self.loginHeader.setScaledContents(True)
        self.loginHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.loginHeader.setObjectName("loginHeader")
        self.stackedWidget.addWidget(self.page_login)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.page_2_tabs = QtWidgets.QTabWidget(self.page_2)
        self.page_2_tabs.setGeometry(QtCore.QRect(10, 0, 600, 500))
        self.page_2_tabs.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.page_2_tabs.setAutoFillBackground(False)
        self.page_2_tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.page_2_tabs.setTabsClosable(False)
        self.page_2_tabs.setObjectName("page_2_tabs")
        self.messages_tab = QtWidgets.QWidget()
        self.messages_tab.setObjectName("messages_tab")
        self.messageInput = QtWidgets.QTextEdit(self.messages_tab)
        self.messageInput.setGeometry(QtCore.QRect(10, 430, 481, 31))
        self.messageInput.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.messageInput.setStyleSheet("")
        self.messageInput.setObjectName("messageInput")
        self.sendButton = QtWidgets.QPushButton(self.messages_tab)
        self.sendButton.setGeometry(QtCore.QRect(500, 430, 91, 31))
        self.sendButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/outline_send_black_18dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sendButton.setIcon(icon)
        self.sendButton.setAutoDefault(False)
        self.sendButton.setObjectName("sendButton")
        self.messages = QtWidgets.QTextEdit(self.messages_tab)
        self.messages.setEnabled(True)
        self.messages.setGeometry(QtCore.QRect(0, 0, 600, 421))
        self.messages.setAccessibleName("")
        self.messages.setAccessibleDescription("")
        self.messages.setReadOnly(True)
        self.messages.setObjectName("messages")
        self.page_2_tabs.addTab(self.messages_tab, "")
        self.charts_tab = QtWidgets.QWidget()
        self.charts_tab.setObjectName("charts_tab")
        self.page_2_tabs.addTab(self.charts_tab, "")
        self.account_tab = QtWidgets.QWidget()
        self.account_tab.setObjectName("account_tab")
        self.frame = QtWidgets.QFrame(self.account_tab)
        self.frame.setGeometry(QtCore.QRect(20, 20, 561, 431))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 6, 111, 21))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(20, 40, 111, 31))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setEditable(False)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(10, 30, 151, 2))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.save_button = QtWidgets.QPushButton(self.frame)
        self.save_button.setGeometry(QtCore.QRect(450, 390, 89, 25))
        self.save_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_button.setObjectName("save_button")
        self.logOut = QtWidgets.QPushButton(self.frame)
        self.logOut.setGeometry(QtCore.QRect(20, 390, 89, 25))
        self.logOut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logOut.setObjectName("logOut")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 81, 17))
        self.label_2.setObjectName("label_2")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(10, 130, 151, 2))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame)
        self.comboBox_3.setGeometry(QtCore.QRect(20, 140, 111, 31))
        self.comboBox_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.admin_delete_messages = QtWidgets.QPushButton(self.frame)
        self.admin_delete_messages.setGeometry(QtCore.QRect(130, 390, 161, 25))
        self.admin_delete_messages.setObjectName("admin_delete_messages")
        self.page_2_tabs.addTab(self.account_tab, "")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionLog_Iyt = QtWidgets.QAction(MainWindow)
        self.actionLog_Iyt.setObjectName("actionLog_Iyt")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionEN = QtWidgets.QAction(MainWindow)
        self.actionEN.setObjectName("actionEN")
        self.actionKA = QtWidgets.QAction(MainWindow)
        self.actionKA.setObjectName("actionKA")
        self.actionEdit_2 = QtWidgets.QAction(MainWindow)
        self.actionEdit_2.setObjectName("actionEdit_2")
        self.actionLog_Put = QtWidgets.QAction(MainWindow)
        self.actionLog_Put.setObjectName("actionLog_Put")
        self.actionKA_2 = QtWidgets.QAction(MainWindow)
        self.actionKA_2.setObjectName("actionKA_2")
        self.actionED = QtWidgets.QAction(MainWindow)
        self.actionED.setObjectName("actionED")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.page_2_tabs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.inputUsername.setPlaceholderText(_translate("MainWindow", "username"))
        self.inputPassword.setPlaceholderText(_translate("MainWindow", "password"))
        self.createButton.setText(_translate("MainWindow", "Create"))
        self.loginHeader.setText(_translate("MainWindow", "Login"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.sendButton.setShortcut(_translate("MainWindow", "Return"))
        self.messages.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica\'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.page_2_tabs.setTabText(self.page_2_tabs.indexOf(self.messages_tab), _translate("MainWindow", "Messages"))
        self.page_2_tabs.setTabText(self.page_2_tabs.indexOf(self.charts_tab), _translate("MainWindow", "Charts"))
        self.label.setText(_translate("MainWindow", "Language"))
        self.comboBox.setItemText(0, _translate("MainWindow", "English"))
        self.comboBox.setItemText(1, _translate("MainWindow", "ქართული"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.logOut.setText(_translate("MainWindow", "Log Out"))
        self.label_2.setText(_translate("MainWindow", "User color"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Blue"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Green"))
        self.admin_delete_messages.setText(_translate("MainWindow", "Delete Messages"))
        self.page_2_tabs.setTabText(self.page_2_tabs.indexOf(self.account_tab), _translate("MainWindow", "Account"))
        self.actionLog_Iyt.setText(_translate("MainWindow", "Log out"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actionEN.setText(_translate("MainWindow", "EN"))
        self.actionKA.setText(_translate("MainWindow", "KA"))
        self.actionEdit_2.setText(_translate("MainWindow", "Edit"))
        self.actionLog_Put.setText(_translate("MainWindow", "Log Out"))
        self.actionKA_2.setText(_translate("MainWindow", "KA"))
        self.actionED.setText(_translate("MainWindow", "EN"))