# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        MainWindow.setStyleSheet("*{\n"
"    font-family: Arial;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#page_login {\n"
"    border-image: url(\'./assets/images/bck.jpg\') 0 0 0 0 stretch stretch;    \n"
"}\n"
"\n"
"#page_messages {\n"
"    background-color: rgb(211, 215, 207)\n"
"}\n"
"\n"
"#loginWrapper {\n"
"    background-color: rgba(0, 0, 0, 0.7);\n"
"    border: 0;\n"
"}\n"
"\n"
"#loginHeader{\n"
"    color: rgb(17, 132, 224);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background: transparent;\n"
"    border: 0 ;\n"
"    border-bottom: 1px solid rgb(186, 189, 182);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 0;\n"
"    background-color: rgb(114, 159, 207);\n"
"}\n"
"\n"
"#createButton {\n"
"    background-color: rgb(65, 208, 124);\n"
"}\n"
"\n"
"#loginButton {\n"
"    background-color: rgb(17, 132, 224);\n"
"}\n"
"\n"
"#backButton {\n"
"    border: 0;\n"
"}\n"
"\n"
"#sendButton {\n"
"    background-color: rgb(17, 132, 224);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"#sendButton:hover {\n"
"    background-color: rgb(107, 159, 255);\n"
"}\n"
"\n"
"#messages {\n"
"    border: 0;\n"
"    background-color: white;\n"
"}\n"
"\n"
"#messageInput {\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"#menuBar {\n"
"    border: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: white;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-10, 0, 611, 501))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.loginWrapper = QtWidgets.QFrame(self.page_login)
        self.loginWrapper.setGeometry(QtCore.QRect(150, 80, 351, 341))
        self.loginWrapper.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.loginWrapper.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginWrapper.setFrameShadow(QtWidgets.QFrame.Plain)
        self.loginWrapper.setObjectName("loginWrapper")
        self.loginButton = QtWidgets.QPushButton(self.loginWrapper)
        self.loginButton.setGeometry(QtCore.QRect(220, 290, 89, 25))
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setObjectName("loginButton")
        self.inputUsername = QtWidgets.QLineEdit(self.loginWrapper)
        self.inputUsername.setGeometry(QtCore.QRect(40, 130, 270, 25))
        self.inputUsername.setStyleSheet("")
        self.inputUsername.setObjectName("inputUsername")
        self.inputPassword = QtWidgets.QLineEdit(self.loginWrapper)
        self.inputPassword.setGeometry(QtCore.QRect(40, 210, 270, 25))
        self.inputPassword.setMouseTracking(True)
        self.inputPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPassword.setClearButtonEnabled(False)
        self.inputPassword.setObjectName("inputPassword")
        self.createButton = QtWidgets.QPushButton(self.loginWrapper)
        self.createButton.setGeometry(QtCore.QRect(40, 290, 89, 25))
        self.createButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.createButton.setObjectName("createButton")
        self.loginHeader = QtWidgets.QLabel(self.loginWrapper)
        self.loginHeader.setGeometry(QtCore.QRect(46, 50, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.loginHeader.setFont(font)
        self.loginHeader.setTextFormat(QtCore.Qt.AutoText)
        self.loginHeader.setScaledContents(True)
        self.loginHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.loginHeader.setObjectName("loginHeader")
        self.stackedWidget.addWidget(self.page_login)
        self.page_messages = QtWidgets.QWidget()
        self.page_messages.setObjectName("page_messages")
        self.messageInput = QtWidgets.QTextEdit(self.page_messages)
        self.messageInput.setGeometry(QtCore.QRect(20, 460, 481, 31))
        self.messageInput.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.messageInput.setStyleSheet("")
        self.messageInput.setObjectName("messageInput")
        self.sendButton = QtWidgets.QPushButton(self.page_messages)
        self.sendButton.setGeometry(QtCore.QRect(510, 460, 91, 31))
        self.sendButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap('./assets/images/outline_send_black_18dp.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sendButton.setIcon(icon)
        self.sendButton.setAutoDefault(False)
        self.sendButton.setObjectName("sendButton")
        self.line = QtWidgets.QFrame(self.page_messages)
        self.line.setGeometry(QtCore.QRect(0, 430, 611, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.messages = QtWidgets.QFrame(self.page_messages)
        self.messages.setGeometry(QtCore.QRect(10, 0, 601, 451))
        self.messages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.messages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.messages.setObjectName("messages")
        self.backButton = QtWidgets.QToolButton(self.messages)
        self.backButton.setGeometry(QtCore.QRect(5, 5, 26, 24))
        self.backButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./assets/images/arrow_back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon1)
        self.backButton.setObjectName("backButton")
        self.stackedWidget.addWidget(self.page_messages)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionLog_Iyt = QtWidgets.QAction(MainWindow)
        self.actionLog_Iyt.setObjectName("actionLog_Iyt")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionEN = QtWidgets.QAction(MainWindow)
        self.actionEN.setObjectName("actionEN")
        self.actionKA = QtWidgets.QAction(MainWindow)
        self.actionKA.setObjectName("actionKA")
        self.actionEdit_2 = QtWidgets.QAction(MainWindow)
        self.actionEdit_2.setObjectName("actionEdit_2")
        self.actionLog_Put = QtWidgets.QAction(MainWindow)
        self.actionLog_Put.setObjectName("actionLog_Put")
        self.actionKA_2 = QtWidgets.QAction(MainWindow)
        self.actionKA_2.setObjectName("actionKA_2")
        self.actionED = QtWidgets.QAction(MainWindow)
        self.actionED.setObjectName("actionED")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.inputUsername.setPlaceholderText(_translate("MainWindow", "username"))
        self.inputPassword.setPlaceholderText(_translate("MainWindow", "password"))
        self.createButton.setText(_translate("MainWindow", "Create"))
        self.loginHeader.setText(_translate("MainWindow", "Login"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.sendButton.setShortcut(_translate("MainWindow", "Return"))
        self.actionLog_Iyt.setText(_translate("MainWindow", "Log out"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actionEN.setText(_translate("MainWindow", "EN"))
        self.actionKA.setText(_translate("MainWindow", "KA"))
        self.actionEdit_2.setText(_translate("MainWindow", "Edit"))
        self.actionLog_Put.setText(_translate("MainWindow", "Log Out"))
        self.actionKA_2.setText(_translate("MainWindow", "KA"))
        self.actionED.setText(_translate("MainWindow", "EN"))
